# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6b6790ee473869972d29c52928582164866053e2c597c4ef81a34d205ce4d679e030e149ab2d7fb04ef1963178bae1407b18876a76d0a8cd8b22545b8849cc8

test:
  secret_key_base: 459dbc76d947dbf8ff27b494a63d456be39e01ad45184b511c8066d6ce0a22c8bf46a1b80f4c9069ca4a3cb4708038221bbbc9f23ac9a2942501d468d67bd7f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
